name: ${project.artifactId}
main: ${mainClass}
version: ${project.version}
author: ${author}
depend: [packetevents]
softdepend: [Floodgate]
api-version: 1.13
folia-supported: true
commands:
  replay:
    description: Replay base command

permissions:
  replay.*:
    description: Gives access to all replay commands
    children:
      replay.start: true
      replay.stop: true
      replay.list: true
      replay.delete: true
      replay.play: true
      replay.export: true
      replay.benchmark: true
      replay.debug: true
  replay.start:
    description: Allows starting a new recording
    default: op
  replay.stop:
    description: Allows stopping an active recording
    default: op
  replay.list:
    description: Allows listing saved replays
    default: op
  replay.play:
    description: Play a recording
    default: op
  replay.delete:
    description: Allows deleting saved replays
    default: op
  replay.export:
    description: Allows running the hidden replay export command
    default: op
  replay.benchmark:
    description: Allows running the hidden replay benchmark command
    default: op
  replay.debug:
    description: Allows running the hidden replay debug dump command
    default: op