name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 26
          distribution: 'temurin'

      - name: Build
        run: mvn install

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: BetterReplay
          path: target/*.jar
