name: Build

on:
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Build
        run: mvn install

      - uses: actions/upload-artifact@v4
        name: Upload Artifact
        with:
          name: BetterReplay
          path: target/*.jar
